language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
install:
  - pip install pytest pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
script: py.test --cov=vidua
